apiVersion: v1
kind: ConfigMap
metadata:
  name: deutsch-conf
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;

        root /bucket/web;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        error_page 404 /index.html;
    }
