apiVersion: apps/v1
kind: Deployment
metadata:
  name: deutsch-deployment
  labels:
    app.kubernetes.io/instance: deutsch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deutsch
  template:
    metadata:
      labels:
        app: deutsch
    spec:
      containers:
        - name: deutsch-container
          image: nginx:alpine
          volumeMounts:
            - mountPath: /bucket
              name: deutsch-storage-lg

            - name: deutsch-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: deutsch-storage-lg
          persistentVolumeClaim:
            claimName: deutsch-pvc-lg

        - name: deutsch-conf
          configMap:
            name: deutsch-conf
            items:
              - key: nginx.conf
                path: nginx.conf
