apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deutsch-pvc-lg
  labels:
    app.kubernetes.io/instance: deutsch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
