apiVersion: v1
kind: Service
metadata:
  name: deutsch
  labels:
    app: deutsch
    app.kubernetes.io/instance: deutsch
spec:
  type: NodePort
  selector:
    app: deutsch
  ports:
    - protocol: TCP
      port: 80
